# Generated by Django 5.0.7 on 2024-11-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Kanal', 'verbose_name_plural': 'Kanallar'},
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
